apiVersion: v1
data:
    password: ENC[AES256_GCM,data:mOVZu7yalqY1kti3,iv:+Lzi1TJ89420hK0B/fkVBOm3rW0Y8oGFnw/KS1W5VJE=,tag:MFmBNaiqCvQhBE9c4rx3xA==,type:str]
    user: ENC[AES256_GCM,data:gbmdsiR3K/4=,iv:2DZbQ7JQjvRGX61MiwY3a/eyxcMwt6PwVNX+jmt+b04=,tag:ZZ+t46d3huMhQxuppcgnLg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T08:48:31Z"
    mac: ENC[AES256_GCM,data:OdQtSKcRuvzA1mnKewHPGVWY5Im/heZ8dJhg8v1nfTO5JlKisV2bNqmEHtwnHu24+NLeqRWxJ08bzrLPF2kaims/VNSbggy/iw5wZXpdeKPIAr/IGSKcypa7jbituJ7b67m0569Ia3hU8L+CZnDYpE6jcQWvMkIQqiNYfEuqLHU=,iv:/CvzRULip8yESECt7xYsEaIQn+/BTwCnDw5tL3xAb7c=,tag:eqvnHAfuvFnUiUK9qZ17kA==,type:str]
    pgp:
        - created_at: "2021-07-30T08:48:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6hCbqO64WwsARAAzIJcVeA1z5Bc+3Qz91BIiroWSrH/4sEJVBJ8K2g5eTJx
            gDMy9YzEUxYCCH/y4Wd7Gf5y1NeJzqlbQ9bD+OYwpOCeP6KTJZbR/yd20ZuWMrMd
            F91ZOLoNlH+ppU4h3iuWwAN+CMLPwbMxknG5Gch/PqHm5I1RcAMg63nfpsjhzExu
            qZWxensLn8tu1o5aggaV3gQ2pog245V889paeLvh04m8a8RaY4DSZpB5ugAXVj+J
            MXXo+sfCNGE8FX9NFyvi+VLsaxtxFxeYtAVfz2R5y5POYLE2Y+1AWj1XlOSZqysx
            AbxWLxQvytcu55+4+8uB0mymQzB82KVXOQ4xgltuao/98EWz8xAftzWVzmV2ZT++
            5pD2QJ1TCtYRtuKVqK7ZpvqnUSFfwD1eoA+R7arpknipywiI/5XvL/cM/MoJerIW
            by7SdpMqQk28Ck9/LxGWifhMEmzmpLG09s2J56lceQeqlJt8x+exO/VA84NvMtU3
            cAYTKjgxUS6gfwydNHkZPHYLW4mRIIiEqUuvxJg/OT3LHm/qdosFBHO8sxk6Dzck
            si228hWEKwwu1KzZNKFFXIOcpdf/cXEQSZNeAUnGISoKl2yi6Ke1+g57q3in1YI6
            F/1WDU4F0kMyIuJrPlkqMKOwDsDNtHjr4Fo1V7aX3UkTUGj1LoU5KXBflhiJKg3S
            5gFc7rrtSnmwpNiusL2f8ZXC1/CQOP4txlV2EkDBWIJBNXOMaC9at6/RNL1QeyCn
            sdZcR9tpz/iBoQqt9a82xmbkRwIs3F7q/tealFlEmlzoU+KQI7oUAA==
            =LRXJ
            -----END PGP MESSAGE-----
          fp: 86FDA9C367BD2B1FD2F8F36FDC0A3CFB8F1CC9F3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
